# Generated by Django 5.2.10 on 2026-01-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('logo', models.URLField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(max_length=50)),
                ('stage', models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'MVP'), ('early', 'Early Stage'), ('growth', 'Growth Stage'), ('scale', 'Scale Up')], default='idea', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hiring', 'Actively Hiring'), ('stealth', 'Stealth Mode'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_remote', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('pitch_deck_url', models.URLField(blank=True, null=True)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'startups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StartupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('cofounder', 'Co-Founder'), ('cto', 'CTO'), ('developer', 'Developer'), ('designer', 'Designer'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'startup_members',
            },
        ),
        migrations.CreateModel(
            name='StartupUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'startup_updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
