# Generated by Django 5.2.10 on 2026-01-25 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founded_startups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupmember',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupupdate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupupdate',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='startups.startup'),
        ),
        migrations.AlterUniqueTogether(
            name='startupmember',
            unique_together={('startup', 'user')},
        ),
    ]
