# Generated by Django 5.2.10 on 2026-01-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('type', models.CharField(choices=[('hackathon', 'Hackathon'), ('internship', 'Internship'), ('project', 'Project'), ('job', 'Job'), ('collaboration', 'Collaboration'), ('competition', 'Competition')], max_length=20)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_remote', models.BooleanField(default=True)),
                ('team_size_min', models.PositiveIntegerField(default=1)),
                ('team_size_max', models.PositiveIntegerField(default=5)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('perks', models.JSONField(blank=True, default=list)),
                ('prize_amount', models.CharField(blank=True, max_length=50)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('registration_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('completed', 'Completed')], default='open', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'db_table': 'opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_opportunities',
            },
        ),
    ]
