# Generated by Django 5.2.10 on 2026-01-25 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='opportunities.opportunity'),
        ),
    ]
